# fly.toml app configuration file generated for ims-backend-tranquil-mountain-4123 on 2026-06-08T12:17:09-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ims-backend'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
